use crate::data::GameData;
use crate::network::{ConnectionState, CraftingView, RemotePlayer};
use crate::state::WorldState;
use macroquad_toolkit::grid::TilePos;
use macroquad_toolkit::ui::VirtualUi;
use tarrowyn_protocol::{
    ChatMessage, ChronicleEntry, ChronicleSummary, ExpeditionRequirements, LocalCombatState,
    OpportunitySignal, RegionSnapshot, TimeOfDay, TradeOffer, WildernessZone,
};

#[derive(Debug, Clone, PartialEq)]
pub enum UiAction {
    NewEvening,
    UseOnline,
    UseOffline,
    Reconnect,
    Practice(String),
    Save,
    Load,
    DeleteSave,
    Move(i32, i32),
    MoveTo(TilePos),
    Interact(String),
    RegionalEvent(String),
    SendChat,
    QuickChat(String),
    Zoom(f32),
}

pub struct UiContext<'a> {
    pub data: &'a GameData,
    pub world: &'a WorldState,
    pub player_position: TilePos,
    pub day: u32,
    pub calendar_season: Option<&'a str>,
    pub clock_minutes: u32,
    pub time_of_day: TimeOfDay,
    pub night: bool,
    pub stats: &'a str,
    pub own_account_id: Option<&'a str>,
    pub player_position_authoritative: bool,
    pub remote_players: &'a [RemotePlayer],
    pub farm_animals: &'a [tarrowyn_protocol::FarmAnimal],
    pub trades: &'a [TradeOffer],
    pub trade_pending: bool,
    pub farming_pending: bool,
    pub chat: &'a [ChatMessage],
    pub chat_draft: &'a str,
    pub server_tick: u64,
    pub connection: ConnectionState,
    pub status_message: &'a str,
    pub expedition: Option<&'a tarrowyn_protocol::Expedition>,
    pub expedition_requirements: ExpeditionRequirements,
    pub identity_name: Option<&'a str>,
    pub offline: bool,
    pub save_exists: bool,
    pub save_slots: &'a [String],
    pub loaded_assets: usize,
    pub camera_zoom: f32,
    pub wilderness: Option<&'a WildernessZone>,
    pub regional_region: Option<&'a RegionSnapshot>,
    pub regional_inspection: Option<&'a str>,
    pub regional_event_choices: &'a [String],
    pub skills: &'a [tarrowyn_protocol::SkillView],
    pub skill_selection_open: bool,
    pub chronicle_open: bool,
    pub chronicle: &'a [ChronicleEntry],
    pub chronicle_summary: Option<&'a ChronicleSummary>,
    pub chronicle_query: &'a str,
    pub chronicle_search: &'a [ChronicleEntry],
    pub chronicle_search_summary: Option<&'a ChronicleSummary>,
    pub chronicle_search_query: Option<&'a str>,
    pub chronicle_search_next_cursor: Option<u64>,
    pub chronicle_search_pending: bool,
    pub opportunities: &'a [OpportunitySignal],
    pub phase4_summary: &'a str,
    pub phase5_summary: &'a str,
    pub account_deletion_armed: bool,
    pub account_deletion_available: bool,
    pub account_link_available: bool,
    pub account_open: bool,
    pub account_summary: &'a str,
    pub identity_pending: bool,
    pub report_pending: bool,
    pub crafting: Option<CraftingView>,
    pub combat: Option<&'a LocalCombatState>,
    pub storm_magic_unlocked: bool,
    pub skill_pending: bool,
    pub knowledge_pending: bool,
    pub order_pending: bool,
    pub combat_pending: bool,
    pub contract_pending: bool,
    pub expedition_pending: bool,
    pub frontier_combat_pending: bool,
    pub frontier_claim_pending: bool,
    pub knocked_out: bool,
    pub recovery_pending: bool,
    pub has_open_market_order: bool,
    pub market_pending: bool,
    pub event_pending: bool,
    pub route_pending: bool,
    pub governance_pending: bool,
    pub can_abandon_claim: bool,
    pub can_transfer_claim: bool,
    pub claim_pending: bool,
    pub knowledge_label: &'a str,
    pub travel_label: &'a str,
    pub can_travel: bool,
    pub can_recover_travel: bool,
    pub travel_pending: bool,
    pub ui: &'a VirtualUi,
}
